In [29]:
#Importing pandas library for the dataset
import pandas as pd

In [30]:
#Reading the file
dataset=pd.read_csv("border_intrusion_dataset.csv")

In [31]:
#To view the dataset
dataset

,sensor_id,timestamp_hour,motion_intensity,vibration_level,thermal_signature,acoustic_level,object_speed_kmph,distance_m,altitude_m,water_pressure,route_mode,weather_condition,terrain_type,sensor_status,signal_noise_ratio,target_class,weight
0,1001,15,7.87,77.87,710.60,77.87,7.87,710.60,0.00,0.00,Ground,Clear,Mountain,Active,710.60,Human,70
1,1002,6,4.29,75.29,145.61,74.29,4.29,145.61,0.00,0.00,Ground,Clear,Forest,Active,145.61,Human,70
2,1003,21,7.11,79.11,302.38,77.11,7.11,302.38,0.00,0.00,Ground,Clear,Open Field,Active,302.38,Human,70
3,1004,1,4.94,75.94,589.96,74.94,4.94,589.96,0.00,0.00,Ground,Clear,Forest,Active,589.96,Human,70
4,1005,23,5.28,75.28,499.80,75.28,5.28,499.80,0.00,0.00,Ground,Clear,Mountain,Active,499.80,Human,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,1346,6,1.02,61.02,420.29,61.02,1.02,415.29,0.00,0.00,Ground,Clear,Mountain,Active,415.29,False Alarm,60
346,1347,6,1.32,62.32,133.90,61.32,1.32,128.90,0.00,3.05,Water Route,Storm,Forest,Active,130.90,False Alarm,60
347,1348,13,1.84,63.84,368.89,61.84,1.84,363.89,0.00,0.00,Ground,Rain,Open Field,Active,364.89,False Alarm,60
348,1349,14,0.96,60.96,277.58,60.96,0.96,272.58,23.15,0.00,Air Route,Clear,Mountain,Degraded,272.58,False Alarm,60
349,1350,14,0.41,61.41,459.57,60.41,0.41,454.57,0.00,4.76,Water Route,Clear,Forest,Active,454.57,False Alarm,60

In [32]:
# To view Null values
dataset.isnull().sum()

sensor_id              0
timestamp_hour         0
motion_intensity       0
vibration_level        0
thermal_signature      0
acoustic_level         0
object_speed_kmph      0
distance_m             0
altitude_m             0
water_pressure         0
route_mode             0
weather_condition     10
terrain_type           0
sensor_status          0
signal_noise_ratio     0
target_class           0
weight                 0
dtype: int64

In [13]:
import numpy as np  # Imports NumPy to handle numerical data and represent missing values as np.nan
from sklearn.impute import SimpleImputer  # Loads SimpleImputer for filling missing values
imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')  # Creates an imputer that replaces NaN with column median
imp_mean.fit(dataset[['weather_condition']])  # Learns mean values from all quantitative columns in the dataset
df_qual = imp_mean.transform(dataset[['weather_condition']])  # Applies mean replacement to missing values in those columns
df_qual=pd.DataFrame(df_qual,columns=['weather_condition'])
df_qual

    weather_condition
0               Clear
1               Clear
2               Clear
3               Clear
4               Clear
..                ...
345             Clear
346             Storm
347              Rain
348             Clear
349             Clear

[350 rows x 1 columns]

In [16]:
dataset.isnull().sum()

sensor_id              0
timestamp_hour         0
motion_intensity       0
vibration_level        0
thermal_signature      0
acoustic_level         0
object_speed_kmph      0
distance_m             0
altitude_m             0
water_pressure         0
route_mode             0
weather_condition     10
terrain_type           0
sensor_status          0
signal_noise_ratio     0
target_class           0
weight                 0
dtype: int64

In [17]:
#Using for loop to fill the null value
for col in ['weather_condition']:
    dataset.loc[:, col] = dataset[col].fillna(dataset[col].mode()[0])

In [18]:
# To view Null values
dataset.isnull().sum()

sensor_id             0
timestamp_hour        0
motion_intensity      0
vibration_level       0
thermal_signature     0
acoustic_level        0
object_speed_kmph     0
distance_m            0
altitude_m            0
water_pressure        0
route_mode            0
weather_condition     0
terrain_type          0
sensor_status         0
signal_noise_ratio    0
target_class          0
weight                0
dtype: int64

In [19]:
#Using get_dummies to convert text into number
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [20]:
dataset

,sensor_id,timestamp_hour,motion_intensity,vibration_level,thermal_signature,acoustic_level,object_speed_kmph,distance_m,altitude_m,water_pressure,...,weather_condition_Storm,terrain_type_Mountain,terrain_type_Open Field,terrain_type_Riverbank,sensor_status_Degraded,target_class_Animal,target_class_False Alarm,target_class_Human,target_class_Vehicle,target_class_Water Intrusion
0,1001,15,7.87,77.87,710.60,77.87,7.87,710.60,0.00,0.00,...,0,1,0,0,0,0,0,1,0,0
1,1002,6,4.29,75.29,145.61,74.29,4.29,145.61,0.00,0.00,...,0,0,0,0,0,0,0,1,0,0
2,1003,21,7.11,79.11,302.38,77.11,7.11,302.38,0.00,0.00,...,0,0,1,0,0,0,0,1,0,0
3,1004,1,4.94,75.94,589.96,74.94,4.94,589.96,0.00,0.00,...,0,0,0,0,0,0,0,1,0,0
4,1005,23,5.28,75.28,499.80,75.28,5.28,499.80,0.00,0.00,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,1346,6,1.02,61.02,420.29,61.02,1.02,415.29,0.00,0.00,...,0,1,0,0,0,0,1,0,0,0
346,1347,6,1.32,62.32,133.90,61.32,1.32,128.90,0.00,3.05,...,1,0,0,0,0,0,1,0,0,0
347,1348,13,1.84,63.84,368.89,61.84,1.84,363.89,0.00,0.00,...,0,0,1,0,0,0,1,0,0,0
348,1349,14,0.96,60.96,277.58,60.96,0.96,272.58,23.15,0.00,...,0,1,0,0,1,0,1,0,0,0
349,1350,14,0.41,61.41,459.57,60.41,0.41,454.57,0.00,4.76,...,0,0,0,0,0,0,1,0,0,0

In [21]:
qual=['weather_condition_Fog','weather_condition_Rain', 'weather_condition_Storm']

In [22]:
import numpy as np  # Imports NumPy to handle numerical data and represent missing values as np.nan
from sklearn.impute import SimpleImputer  # Loads SimpleImputer for filling missing values
imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')  # Creates an imputer that replaces NaN with column median
imp_mean.fit(dataset[qual])  # Learns mean values from all quantitative columns in the dataset
df_qual = imp_mean.transform(dataset[qual])  # Applies mean replacement to missing values in those columns
df_qual=pd.DataFrame(df_qual,columns=qual)
df_qual

     weather_condition_Fog  weather_condition_Rain  weather_condition_Storm
0                        0                       0                        0
1                        0                       0                        0
2                        0                       0                        0
3                        0                       0                        0
4                        0                       0                        0
..                     ...                     ...                      ...
345                      0                       0                        0
346                      0                       0                        1
347                      0                       1                        0
348                      0                       0                        0
349                      0                       0                        0

[350 rows x 3 columns]

In [24]:
from Univariate import qualQuan1

In [26]:
qual,quan=qualQuan1.qualQuan(dataset)
print(qual,quan)

[] ['sensor_id', 'timestamp_hour', 'motion_intensity', 'vibration_level', 'thermal_signature', 'acoustic_level', 'object_speed_kmph', 'distance_m', 'altitude_m', 'water_pressure', 'signal_noise_ratio', 'weight', 'route_mode_Ground', 'route_mode_Vehicle Route', 'route_mode_Water Route', 'weather_condition_Fog', 'weather_condition_Rain', 'weather_condition_Storm', 'terrain_type_Mountain', 'terrain_type_Open Field', 'terrain_type_Riverbank', 'sensor_status_Degraded', 'target_class_Animal', 'target_class_False Alarm', 'target_class_Human', 'target_class_Vehicle', 'target_class_Water Intrusion']

In [27]:
dataset[quan].cov()

,sensor_id,timestamp_hour,motion_intensity,vibration_level,thermal_signature,acoustic_level,object_speed_kmph,distance_m,altitude_m,water_pressure,...,weather_condition_Storm,terrain_type_Mountain,terrain_type_Open Field,terrain_type_Riverbank,sensor_status_Degraded,target_class_Animal,target_class_False Alarm,target_class_Human,target_class_Vehicle,target_class_Water Intrusion
sensor_id,10237.500000,-12.293696,907.168696,-137.549069,9825.228123,-127.215258,907.168696,9661.904341,14215.441117,805.926533,...,-1.123209,1.495702,0.336676,-4.587393,1.392550,-12.893983,17.765043,-28.080229,-2.005731e+00,15.759312
timestamp_hour,-12.293696,43.664519,8.075132,-19.293030,27.592844,-18.823763,8.075132,27.687318,108.408805,-6.075400,...,0.037609,0.153238,-0.086967,-0.114531,0.008776,-0.138191,0.073107,0.147278,-6.762178e-02,-0.142857
motion_intensity,907.168696,8.075132,1833.129879,4218.544607,22540.706854,4222.730951,1833.129879,22528.878019,17531.738113,-113.359305,...,-0.862696,0.620847,1.485716,-2.525606,-0.526190,-4.288932,-4.111772,-6.384275,5.478533e+00,-2.199779
vibration_level,-137.549069,-19.293030,4218.544607,37640.101956,42675.047354,37651.368766,4218.544607,42685.921425,-5731.975547,-754.047642,...,-2.472962,0.613741,1.351234,-6.002151,-3.186624,-21.144192,-14.254056,-22.064504,7.600461e+01,-14.843250
thermal_signature,9825.228123,27.592844,22540.706854,42675.047354,905754.711615,42745.045339,22540.706854,905657.820758,303823.444158,-542.172599,...,20.185863,-1.734769,22.137681,-46.935217,-29.041266,-81.607316,-98.347494,-63.678774,4.551148e+01,-15.153623
acoustic_level,-127.215258,-18.823763,4222.730951,37651.368766,42745.045339,37663.826088,4222.730951,42755.746181,-5693.926251,-754.682923,...,-2.486110,0.976148,1.208188,-6.344681,-3.243341,-21.186190,-14.230478,-22.086281,7.602295e+01,-14.848162
object_speed_kmph,907.168696,8.075132,1833.129879,4218.544607,22540.706854,4222.730951,1833.129879,22528.878019,17531.738113,-113.359305,...,-0.862696,0.620847,1.485716,-2.525606,-0.526190,-4.288932,-4.111772,-6.384275,5.478533e+00,-2.199779
distance_m,9661.904341,27.687318,22528.878019,42685.921425,905657.820758,42755.746181,22528.878019,905563.628222,303618.713380,-555.142301,...,20.201500,-1.765715,22.117869,-46.854169,-29.057803,-81.396100,-98.665136,-63.231782,4.555733e+01,-15.407409
altitude_m,14215.441117,108.408805,17531.738113,-5731.975547,303823.444158,-5693.926251,17531.738113,303618.713380,466645.172901,-1905.556773,...,-9.139342,5.590123,12.307349,-22.383262,11.188710,-45.098377,-29.171545,-52.614774,-5.261477e+01,-37.581981
water_pressure,805.926533,-6.075400,-113.359305,-754.047642,-542.172599,-754.682923,-113.359305,-555.142301,-1905.556773,347.033858,...,-0.220879,-0.306642,0.103506,0.112567,0.387526,-1.245289,-0.728473,-1.452837,-1.452837e+00,6.124724
signal_noise_ratio,9653.006060,27.715406,22525.149301,42704.805225,905649.688024,42774.578249,22525.149301,905555.658321,303541.820676,-554.477995,...,20.258675,-1.796431,22.143632,-46.856544,-29.077926,-81.420087,-98.693544,-63.193387,4.560719e+01,-15.396357
weight,-1034.383954,-26.898895,2389.601072,33432.824159,20204.338485,33441.095137,2389.601072,20226.868162,-23225.664363,-641.323619,...,-1.623414,0.355301,-0.277528,-3.819075,-2.717151,-16.897257,-10.118707,-15.702006,7.054441e+01,-12.648383
route_mode_Ground,-35.267908,-0.000319,-12.001296,-47.827010,-176.793543,-47.889139,-12.001296,-176.238570,-107.484466,-2.967938,...,0.001670,-0.009513,-0.012223,0.032419,-0.002030,0.101678,-0.009578,0.118625,-8.194842e-02,-0.058535
route_mode_Vehicle Route,-2.005731,-0.067622,5.478533,76.004607,45.511484,76.022946,5.478533,45.557330,-52.614774,-1.452837,...,-0.004011,0.000573,-0.000573,-0.008596,-0.006304,-0.034384,-0.022923,-0.040115,1.604585e-01,-0.028653
route_mode_Water Route,22.040115,-0.119705,-3.638525,-19.815177,-48.435435,-19.828456,-3.638525,-48.800396,-48.104936,5.935876,...,-0.003340,-0.006762,0.010119,-0.001801,0.006926,-0.031437,0.019157,-0.036676,-3.667622e-02,0.117069
weather_condition_Fog,-2.063037,-0.022333,-0.473075,6.950813,-13.419158,6.940760,-0.473075,-13.382891,-14.112841,0.116032,...,-0.050692,-0.001834,0.011985,-0.001883,-0.005289,-0.004994,-0.008105,0.005158,1.661891e-02,0.002047
weather_condition_Rain,-1.159026,0.131355,1.250533,0.946031,21.912248,0.951720,1.250533,21.939264,13.825045,0.108936,...,-0.050102,-0.012607,0.007081,-0.012689,0.003602,0.018420,-0.013508,-0.011461,3.499270e-18,0.002456
weather_condition_Storm,-1.123209,0.037609,-0.862696,-2.472962,20.185863,-2.486110,-0.862696,20.201500,-9.139342,-0.220879,...,0.163864,-0.003668,-0.010823,0.010151,-0.001163,-0.003848,0.005076,0.010315,-4.011461e-03,-0.006549
terrain_type_Mountain,1.495702,0.153238,0.620847,0.613741,-1.734769,0.976148,0.620847,-1.765715,5.590123,-0.306642,...,-0.003668,0.182923,-0.069456,-0.055014,-0.010430,-0.009742,0.009742,0.000573,5.730659e-04,-0.005731
terrain_type_Open Field,0.336676,-0.086967,1.485716,1.351234,22.137681,1.208188,1.485716,22.117869,12.307349,0.103506,...,-0.010823,-0.069456,0.205886,-0.066148,-0.003979,-0.003766,-0.007286,-0.006304,-5.730659e-04,0.007368
terrain_type_Riverbank,-4.587393,-0.114531,-2.525606,-6.002151,-46.935217,-6.344681,-2.525606,-46.854169,-22.383262,0.112567,...,0.010151,-0.055014,-0.066148,0.176832,0.025133,0.018011,-0.003275,0.014327,-8.595989e-03,-0.004093
sensor_status_Degraded,1.392550,0.008776,-0.526190,-3.186624,-29.041266,-3.243341,-0.526190,-29.057803,11.188710,0.387526,...,-0.001163,-0.010430,-0.003979,0.025133,0.092542,-0.003357,0.002538,0.002292,-6.303725e-03,0.005321
target_class_Animal,-12.893983,-0.138191,-4.288932,-21.144192,-81.607316,-21.186190,-4.288932,-81.396100,-45.098377,-1.245289,...,-0.003848,-0.009742,-0.003766,0.018011,-0.003357,0.142448,-0.019648,-0.034384,-3.438395e-02,-0.024560
target_class_False Alarm,17.765043,0.073107,-4.111772,-14.254056,-98.347494,-14.230478,-4.111772,-98.665136,-29.171545,-0.728473,...,0.005076,0.009742,-0.007286,-0.003275,0.002538,-0.019648,0.101515,-0.022923,-2.292264e-02,-0.016373
target_class_Human,-28.080229,0.147278,-6.384275,-22.064504,-63.678774,-22.086281,-6.384275,-63.231782,-52.614774,-1.452837,...,0.010315,0.000573,-0.006304,0.014327,0.002292,-0.034384,-0.022923,0.160458,-4.011461e-02,-0.028653
target_class_Vehicle,-2.005731,-0.067622,5.478533,76.004607,45.511484,76.022946,5.478533,45.557330,-52.614774,-1.452837,...,-0.004011,0.000573,-0.000573,-0.008596,-0.006304,-0.034384,-0.022923,-0.040115,1.604585e-01,-0.028653
target_class_Water Intrusion,15.759312,-0.142857,-2.199779,-14.843250,-15.153623,-14.848162,-2.199779,-15.407409,-37.581981,6.124724,...,-0.006549,-0.005731,0.007368,-0.004093,0.005321,-0.024560,-0.016373,-0.028653,-2.865330e-02,0.122800

In [ ]:
dataset.